### ISSUE TITLE
duplicated sdk in your Dockerfile

### ISSUE THREAD

**Issue by walfud** [ahazem/android-dockerfile#3]
I don't know why you download directly from 'http://dl.google.com/android/android-sdk_r22.3-linux.tgz' by `wget` and `android update sdk .... android-19`?
I think you will get both android-19 & android-22 at last.
Is't correct?

**Comment by ahazem** [comment]
Not really. There's a difference between Android SDK Tools and the Android Platform. The first download gets you the SDK Tools for `KitKat` (4.4.2) while the second gets you the `Kitkat` Platform itself (which is called `android-19`) among other dependencies.

**Comment by walfud** [comment]
Oh, yes... you're right. I learned a lot from your code.
thank you very much.
